CREATE SCHEMA IF NOT EXISTS quotes;


create table quotes.users
(
    registration_time TIMESTAMP,
    user_id           bigint generated by default as identity,
    email             varchar(255) not null unique,
    name              varchar(255) not null,
    password_hash     varchar(255) not null,
    primary key (user_id)
);

create table quotes.quote
(
    creation_time TIMESTAMP,
    quote_id      bigint generated by default as identity,
    content       text not null,
    user_id       bigint  not null,
    primary key (quote_id)
);
--
create table quotes.vote
(
    creation_time TIMESTAMP,
    vote_id       bigint generated by default as identity,
    vote_value         integer not null,
    user_id       bigint  not null,
    quote_id      bigint  not null,

    primary key (vote_id),
    unique (user_id, quote_id)
);

alter table quotes.vote
    add constraint FK_vote_user
        foreign key (user_id)
            references quotes.users (user_id);

alter table quotes.vote
    add constraint FK_vote_quote
        foreign key (quote_id)
            references quotes.quote (quote_id);

alter table quotes.quote
    add constraint FK_quote_user
        foreign key (user_id)
            references quotes.users (user_id);

insert into quotes.users (email, name, password_hash, registration_time, user_id)
values ('qwert@mail.com', 'user1', '12345', '2023-12-07T13:41:30.103674', default);

insert into quotes.users (email, name, password_hash, registration_time, user_id)
values ('wwee@mail.com', 'user2', '12345', '2023-12-08T13:41:30.103674', default);

insert into quotes.quote (user_id,content,creation_time,quote_id)
values (1,'content1','2023-12-08T13:41:30.103674',default);

insert into quotes.quote (user_id,content,creation_time,quote_id)
values (2,'content2','2023-12-08T13:41:30.103674',default);

insert into quotes.vote (vote_id,creation_time, vote_value, user_id, quote_id)
values (default,'2023-12-08T13:41:30.103674',1,1,1);

insert into quotes.vote (vote_id,creation_time, vote_value, user_id, quote_id)
values (default,'2023-12-08T13:41:30.103674',-1,1,2);

insert into quotes.vote (vote_id,creation_time, vote_value, user_id, quote_id)
values (default,'2023-12-08T13:41:30.103674',1,2,1);

insert into quotes.vote (vote_id,creation_time, vote_value, user_id, quote_id)
values (default,'2023-12-08T13:41:30.103674',1,2,2);